Basic methods for TagEntity (correction)
wjfatuan/tasky-backend pull request #6
Opened 2022-05-09 16:33 UTC by Larcos64

TagEntity, repository and controller updated and corrected

2022-05-09 16:55 UTC, wjfatuan requested changes

2022-05-09 16:55 UTC, wjfatuan commented on Procfile
> -web: java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/tasky-0.0.1-SNAPSHOT.jar
Este cambio no se necesita. Retirarlo del PR.

2022-05-09 16:55 UTC, wjfatuan commented on src/main/java/co/edu/uan/software/tasky/controllers/TagController.java
>      @PostMapping("/tag")
Este debería estar mapeado a /tags, igual que el GET.

2022-05-10 04:51 UTC, Larcos64 commented
Corrections made, PR omitted.

2022-05-10 04:51 UTC, closed without merging